### ISSUE TITLE
Only sync from CiviCRM to WP

### ISSUE THREAD

**Issue by kcristiano** [WPCV/wpcv-tax-field-sync#1]
Problem:

Radio Button and Select Custom fields fail to sync properly WP to CiviCRM,  WP 6.1.1, CiviCRM 5.58.1+   Cureently any change will 'blank out' the CiviCRM custom data.

Using checkbox/multi-select does work, but some custom fields are really `active` or `inactive`.  In our case `active` or `lapsed` and Vocal Parts (which is a select and a single part.

proposed solution is to not sync WP to CiviCRM.

https://chat.tadpole.cc/tadpole/pl/g5wid3za9tgazk6rc11wwnpioy

```php
function my_disable_wp_to_civi_tax_sync() {

    // Get the array of sync objects.
    $sync_objects = wpcv_tax_field_sync()->sync_objects;
    if ( empty( $sync_objects ) ) {
        return;
    }
    
    // Remove WordPress-to-CiviCRM sync callbacks.
    foreach( $sync_objects as $sync_object ) {
        $sync_object->mapper->hooks_wordpress_remove();
    }
    
}

add_action( 'wpcv_tax_field_sync/mapper/loaded', 'my_disable_wp_to_civi_tax_sync' );
```

```php
function tc2_disable_wp_to_civi_tax_sync() {

	// Get the array of sync objects.
	$sync_objects = wpcv_tax_field_sync()->sync_objects;
	if ( empty( $sync_objects ) ) {
			return;
	}

	// Remove WordPress-to-CiviCRM sync callbacks.
	foreach( $sync_objects as $sync_object ) {
			$sync_object->mapper->hooks_wordpress_remove();
	}
	var_dump($sync_object);
	die;

}


add_action( 'wpcv_tax_field_sync/mapper/loaded', 'tc2_disable_wp_to_civi_tax_sync' );
```

results:

```log
--empty--
```

No changes to behavior.   We remove custom fields in CiviCRM on Singers CPT save **if using radio buttons/select** and update if using checkbox/multi-select

`if ( empty( $sync_objects ) ) {`

is returning true - I added a `die()` and screen dump there and saw an empty array.

Moving on 

https://chat.tadpole.cc/tadpole/pl/ft6hpruj7bd7p8n7mi4yx7ht4w

```php
function my_disable_wp_to_civi_tax_sync( $sync_object, $taxonomy, $custom_field_id ) {

    // Is this the sync object we want?
    if ( 'my-tax' !== $taxonomy && 123 !== (int) $custom_field_id ) {
        return;
    }

    // Remove WordPress-to-CiviCRM sync callbacks.
    $sync_object->mapper->hooks_wordpress_remove();

}

add_action( 'wpcv_tax_field_sync/base/loaded', 'my_disable_wp_to_civi_tax_sync', 10, 3 );
```

So 
```php
function tc_disable_wp_to_civi_tax_sync( $sync_object, $taxonomy, $custom_field_id ) {

	// Is this the sync object we want?

	if ( 'status' !== $taxonomy && 18 !== (int) $custom_field_id ) {
			return;
	}

	// Remove WordPress-to-CiviCRM sync callbacks.
	$sync_object->mapper->hooks_wordpress_remove();

}

add_action( 'wpcv_tax_field_sync/base/loaded', 'tc_disable_wp_to_civi_tax_sync', 10, 3 );

```

results:

```log

[23-Mar-2023 20:24:05 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function tc_disable_wp_to_civi_tax_sync(), 1 passed in /home/client/public_html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected in /home/client/public_html/wp-content/plugins/tc-wpcv-tax-field-sync/tc-wpcv-tax-field-sync.php:36
Stack trace:
#0 /home/client/public_html/wp-includes/class-wp-hook.php(308): tc_disable_wp_to_civi_tax_sync('')
#1 /home/client/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /home/client/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/client/public_html/wp-content/plugins/wpcv-tax-field-sync/includes/class-sync-base.php(85): do_action('wpcv_tax_field_...')
#4 /home/client/public_html/wp-content/plugins/wpcv-tax-field-sync/includes/class-sync-base.php(61): WPCV_Tax_Field_Sync_Base->initialise('section', 7)
#5 /home/client/public_html/wp-content/plugins/wpcv-tax-field-sync/wpcv-tax-field-sync.php(174): WPCV_Tax_Field_Sync_Base->__construct('section', 7)
#6 /home/client/publ in /home/client/public_html/wp-content/plugins/tc-wpcv-tax-field-sync/tc-wpcv-tax-field-sync.php on line 36
```

The above failed on section not being excluded

Will work on more next week.

This was all done on test site.

**Comment by kcristiano** [comment]
@christianwach this is non-urgent.   Logging so we don't lose the code/logs etc

**Comment by christianwach** [comment]
@kcristiano Yeah ignore the `wpcv_tax_field_sync/mapper/loaded` action stuff. It's not helpful.

> Uncaught ArgumentCountError: Too few arguments

You've definitely got the latest commits? Because there are definitely 3 params:

https://github.com/WPCV/wpcv-tax-field-sync/blob/main/includes/class-sync-base.php#L88

**Comment by kcristiano** [comment]
* f8d085d - (HEAD -> main, origin/main, origin/HEAD) Add current object to action (18 hours ago) <Christian Wach>

That's the last commit.

**Comment by kcristiano** [comment]
Ok after a server restart - (restarting apache2, php-fpm, mysql failed to resolve) - no fatal errors.

But WP to CiviCRM is still syncing....

scratching head on this.
